[Variables]


Player=Spotify


Colour=255,255,255
;default: 255,255,255
;Must be RGB, not hex or RGBA
Alpha=255
Default=255
Colour2=fff9a2
;default: fff9a2
BackgroundColour=d98f84
;default: 9bbede
;Vulfpeck colours: 9bbede, 9cbfdc, d98f84, caddec, f0d3ce, e0e5e7, d85961
;need to run BackgroundChanger for this to update (RefreshAll.ini runs this on click)
BackgroundNoise=1,3
;default:1,3


Font=Vulf Mono
Font2=Roboto Mono
LargeFontSize=56
SmallFontSize=20


CoverScale=0.75
;Default:0.75
LogoScale=0.5
;Default:0.5
Padding=56
;Default: 56